<font size=3>**IMPORTID**<font>

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier as RFC
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import accuracy_score
from time import time
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.tree import DecisionTreeClassifier as DTC
from sklearn.svm import SVC
from sklearn.ensemble import HistGradientBoostingClassifier as HGBC
from sklearn.metrics import confusion_matrix
import winsound
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

<font size=3>**FUNKTSIOONID**<font>

In [102]:
def PlotFeatures(dataframe, sub_rows):
    cols = dataframe.columns

    fig, axs = plt.subplots(sub_rows, 2, figsize=(20, 200))
    for i in range(len(cols)-1):
        values = dataframe[cols[i]].to_numpy()
        df = pd.DataFrame({"value" : values, "result" : dataframe["compliance_2021"]})
        df = df.sort_values(by="value")

        for j in range(df["value"].shape[0]):
            if df["result"].iloc[j] == 1:
                axs[i//2, i%2].plot(j, df["value"].iloc[j], "go")
            else:
                axs[i//2, i%2].plot(j, df["value"].iloc[j], "ro", markersize=3)

        axs[i//2, i%2].set_title(cols[i])

    plt.show()

In [145]:
def data_cleaning(file):
    df = pd.read_csv(file).drop(columns=["compliance_2019", "compliance_2020", 
                                                      "Enterococci_2019", "Enterococci_2020", "Escherichia-coli-Colilert_2019",
                                                     "Escherichia-coli-Colilert_2020", "Escherichia-coli_2019", "Escherichia-coli_2020"])

    station_id = df["station_id"]
    df = df.drop(columns="station_id")

    cols = df.columns

    limit = [60, 1.5, 1.5, 300, 10, 30, 350, 8, 40, 3000, 1.75, 2000, 400, 20, 0.15, 10, 5, 3, 300, 80, 4, 10, 20, 9]

    for i in range(len(cols)-1):
        col = np.array(df[cols[i]].values.tolist())
        df[cols[i]] = np.where(col > limit[i//2], np.nan, col).tolist()

    df = df.fillna(df.mean())
    
    return [df, station_id]

In [185]:
def data_cleaning_2(file):
    df = pd.read_csv(file).drop(columns=["compliance_2019", "compliance_2020", "Color-Pt-Co-unit_2019", "Color-Pt-Co-unit_2020",
                                        "Enterococci_2019", "Enterococci_2020", "Escherichia-coli-Colilert_2019",
                                        "Escherichia-coli-Colilert_2020", "Escherichia-coli_2019", "Escherichia-coli_2020"])

    station_id = df["station_id"]
    df = df.drop(columns="station_id")

    cols = df.columns

    limit = [60, 1.5, 1.5, 300, 10, 30, 350, 40, 3000, 1.75, 2000, 400, 20, 0.15, 10, 5, 3, 300, 80, 4, 10, 20, 9]

    for i in range(len(cols)-1):
        col = np.array(df[cols[i]].values.tolist())
        df[cols[i]] = np.where(col > limit[i//2], np.nan, col).tolist()
        
    df = df.fillna(df.mean())
    
    return [df, station_id]

In [48]:
def data_balance(file):
    df = pd.read_csv(file).drop(columns=["compliance_2019", "compliance_2020", 
                                                      "Enterococci_2019", "Enterococci_2020", "Escherichia-coli-Colilert_2019",
                                                     "Escherichia-coli-Colilert_2020", "Escherichia-coli_2019", "Escherichia-coli_2020"])

    
    positive_cases = df[df["compliance_2021"] == 1]
    negative_sample = df[df["compliance_2021"] == 0].sample(132)
    df_bal = pd.concat([positive_cases, negative_sample])
    df_bal.sort_index(inplace=True)
    
    station_id = df_bal["station_id"]
    df_bal = df_bal.drop(columns="station_id")

    cols = df_bal.columns

    limit = [60, 1.5, 1.5, 300, 10, 30, 350, 8, 40, 3000, 1.75, 2000, 400, 20, 0.15, 10, 5, 3, 300, 80, 4, 10, 20, 9]

    for i in range(len(cols)-1):
        col = np.array(df_bal[cols[i]].values.tolist())
        df_bal[cols[i]] = np.where(col > limit[i//2], np.nan, col).tolist()

    df_bal = df_bal.fillna(df_bal.mean())
    
    return [df_bal, station_id]

<font size=6>**1. KATSE**<font>

<font size=3>**ANDMED**<font>

<font size=3>**ANDMETE KUJUTUS**<font>

<font size=3>**TRAIN SETS**<font>

<font size=3>**PARIM RFC**<font> (runtime ~ 1 min) <br>
<font size=1>RFC(max_depth = 18, min_samples_split = 2, min_samples_leaf = 4) <br>
    acc = 84.5<font>

<font size=3>**TESTIMINE**<font>

<font size=6>**2. KATSE**<font>

<font size=3>**ANDMED**<font>

<font size=3>**ANDMETE KUJUTUS**<font>

<font size=3>**TRAIN SETS**<font>

<font size=3>**TESTIMINE**<font>

<font size=6>**3. KATSE**<font>

<font size=3>**ANDMED**<font>

<font size=3>**TRAIN SETS**<font>

<font size=3>**TESTIMINE**<font>

<font size=6>**4. KATSE**<font>

<font size=3>**ANDMED**<font>

<font size=3>**TRAIN SETS**<font>

<font size=3>**ERINEVAD MUDELID**<font>

<font size=2>**RFC**<font> (runtime ~ 6.2 h) <br>
<font size=1>RFC(criterion = "gini", n_estimators = 10, max_depth = 13, min_samples_split = 2, min_samples_leaf = 3) <br>
    acc = 85.9<font>

<font size=2>**KNN**<font>  (runtime ~ 8 min)<br>
<font size=1>KNN(n_neighbors = 13, metric = "euclidean", leaf_size = 28) <br>
    acc = 85.2<font>

<font size=2>**DTC**<font> (runtime ~ 46 s)<br>
<font size=1>DTC(criterion = "gini", max_depth = 8, min_samples_split = 9, min_samples_leaf = 2) <br>
    acc = 82.1<font>

<font size=2>**SVC (auto)**<font> (runtime ~ 1 min) <br>
<font size=1>acc = 73<font>

<font size=2>**SVC (scale)**<font> (runtime ~ 1 s)<br>
<font size=1>acc = 84.7<font>

<font size=6>**5. KATSE**<font>

<font size=3>**ANDMED**<font>

<font size=3>**ANDMETE KUJUTUS**<font>

<font size=3>**TRAIN SETS**<font>

<font size=2>**HGBC**<font> (runtime ~ 48 s) <br>
<font size=1>HGBC(learning_rate = 0.01, max_iter = 100) <br>
    acc = 85<font>

<font size=2>**HGBC**<font> (runtime ~ 10 s) <br>
<font size=1>HGBC(learning_rate = 0.01, max_iter = 100, max_depth = 5) <br>
    acc = 85.2<font>

<font size=3>**TESTIMINE**<font>

<font size=6>**6. KATSE**<font>

<font size=3>**ANDMED**<font>

<font size=3>**ANDMETE KUJUTUS**<font>

<font size=3>**TRAIN SETS**<font>

<font size=2>**HGBC**<font> (runtime ~ 7 s) <br>
<font size=1>HGBC(learning_rate = 0.01) <br>
    acc = 85<font>

<font size=2>**HGBC**<font> (runtime ~ 32 s) <br>
<font size=1>HGBC(learning_rate = 0.01, min_samples_leaf = 9) <br>
    acc = 85.2<font>

<font size=3>**TESTIMINE**<font>

<font size=6>**7. KATSE**<font>

<font size=3>**ANDMED**<font>

In [162]:
train_df = data_cleaning("train.csv")[0]

<font size=3>**TRAIN SETS**<font>

In [163]:
X = train_df.drop(columns="compliance_2021")
y = train_df["compliance_2021"]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2)

<font size=3>**RFC CONFUSION MATRIX**<font>

In [164]:
model = RFC(criterion = "gini", n_estimators = 10, max_depth = 13, 
            min_samples_split = 2, min_samples_leaf = 3).fit(X_train, y_train)

pred = model.predict(X_val)

matrix = confusion_matrix(y_val.values, pred, labels=[1,0])
print("Confusion matrix:\n%s" % matrix)

Confusion matrix:
[[ 0 12]
 [ 0 76]]


<font size=3>**KNN CONFUSION MATRIX**<font>

In [165]:
model = KNN(n_neighbors = 13, metric = "euclidean", leaf_size = 28).fit(X_train, y_train)

pred = model.predict(X_val)

matrix = confusion_matrix(y_val.values, pred, labels=[1,0])
print("Confusion matrix:\n%s" % matrix)

Confusion matrix:
[[ 0 12]
 [ 0 76]]


<font size=3>**SVC (auto) CONFUSION MATRIX**<font>

In [166]:
model = SVC(kernel = "poly", gamma = "auto").fit(X_train, y_train)

pred = model.predict(X_val)

matrix = confusion_matrix(y_val.values, pred, labels=[1,0])
print("Confusion matrix:\n%s" % matrix)

Confusion matrix:
[[ 5  7]
 [12 64]]


<font size=3>**SVC (scale) CONFUSION MATRIX**<font>

In [174]:
model = SVC(kernel = "poly", gamma = "scale").fit(X_train, y_train)

pred = model.predict(X_val)

matrix = confusion_matrix(y_val.values, pred, labels=[1,0])
print("Confusion matrix:\n%s" % matrix)

Confusion matrix:
[[ 1 11]
 [ 0 76]]


<font size=3>**HGBC CONFUSION MATRIX**<font>

In [168]:
model = HGBC(learning_rate = 0.01, max_iter = 100, max_depth = 5).fit(X_train, y_train)

pred = model.predict(X_val)

matrix = confusion_matrix(y_val.values, pred, labels=[1,0])
print("Confusion matrix:\n%s" % matrix)

Confusion matrix:
[[ 0 12]
 [ 0 76]]


<font size=6>**8. KATSE**<font>

<font size=3>**ANDMED**<font>

In [57]:
train_df = data_balance("train.csv")[0]

<font size=3>**TRAIN SETS**<font>

In [58]:
X = train_df.drop(columns="compliance_2021")
y = train_df["compliance_2021"]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2)

<font size=3>**RFC CONFUSION MATRIX**<font>

In [59]:
model = RFC(criterion = "gini", n_estimators = 10, max_depth = 13, 
            min_samples_split = 2, min_samples_leaf = 3).fit(X_train, y_train)

pred = model.predict(X_val)

matrix = confusion_matrix(y_val.values, pred, labels=[1,0])
print("Confusion matrix:\n%s" % matrix)

Confusion matrix:
[[ 4  5]
 [ 8 23]]


<font size=3>**KNN CONFUSION MATRIX**<font>

In [60]:
model = KNN(n_neighbors = 13, metric = "euclidean", leaf_size = 28).fit(X_train, y_train)

pred = model.predict(X_val)

matrix = confusion_matrix(y_val.values, pred, labels=[1,0])
print("Confusion matrix:\n%s" % matrix)

Confusion matrix:
[[ 0  9]
 [ 4 27]]


<font size=3>**SVC (auto) CONFUSION MATRIX**<font>

In [61]:
model = SVC(kernel = "poly", gamma = "auto").fit(X_train, y_train)

pred = model.predict(X_val)

matrix = confusion_matrix(y_val.values, pred, labels=[1,0])
print("Confusion matrix:\n%s" % matrix)

Confusion matrix:
[[ 5  4]
 [11 20]]


<font size=3>**SVC (scale) CONFUSION MATRIX**<font>

In [62]:
model = SVC(kernel = "poly", gamma = "scale").fit(X_train, y_train)

pred = model.predict(X_val)

matrix = confusion_matrix(y_val.values, pred, labels=[1,0])
print("Confusion matrix:\n%s" % matrix)

Confusion matrix:
[[ 1  8]
 [ 0 31]]


<font size=3>**HGBC CONFUSION MATRIX**<font>

In [63]:
model = HGBC(learning_rate = 0.01, max_iter = 100, max_depth = 5).fit(X_train, y_train)

pred = model.predict(X_val)

matrix = confusion_matrix(y_val.values, pred, labels=[1,0])
print("Confusion matrix:\n%s" % matrix)

Confusion matrix:
[[ 2  7]
 [ 4 27]]


<font size=6>**9. KATSE**<font>

<font size=3>**ANDMED**<font>

In [219]:
train_df = data_balance("train.csv")[0]

<font size=3>**TRAIN SETS**<font>

In [220]:
X = train_df.drop(columns="compliance_2021")
y = train_df["compliance_2021"]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2)

<font size=3>**RFC PROBABILITY**<font>

In [221]:
model = RFC(criterion = "gini", n_estimators = 10, max_depth = 13, 
            min_samples_split = 2, min_samples_leaf = 3).fit(X_train, y_train)

pred = pd.DataFrame(model.predict_proba(X_val))[1]

results = pd.DataFrame({"pred" : pred, "true" : y_val.reset_index(drop=True)})

results

pred  true
0   0.305588     1
1   0.212500     0
2   0.386508     0
3   0.600909     1
4   0.306898     0
5   0.537262     1
6   0.445671     0
7   0.151667     0
8   0.423214     1
9   0.220000     0
10  0.220714     0
11  0.214286     0
12  0.339048     1
13  0.179167     1
14  0.559560     0
15  0.193333     0
16  0.372619     0
17  0.139286     0
18  0.187500     1
19  0.033333     0
20  0.200000     0
21  0.364484     0
22  0.409167     0
23  0.395833     0
24  0.621667     0
25  0.588214     1
26  0.114286     0
27  0.308333     0
28  0.487453     0
29  0.347500     0
30  0.484405     1
31  0.295000     0
32  0.225714     0
33  0.330952     0
34  0.549286     0
35  0.025000     0
36  0.199286     0
37  0.353922     0
38  0.513333     0
39  0.078333     0

<font size=6>**10. KATSE**<font>

<font size=3>**ANDMED**<font>

In [98]:
train_df = pd.read_csv("train.csv").drop(columns=["compliance_2021", "station_id", "Enterococci_2019", "Enterococci_2020", "Escherichia-coli-Colilert_2019",
                                                "Escherichia-coli-Colilert_2020", "Escherichia-coli_2019", "Escherichia-coli_2020"])


cols = train_df.columns

limit = [60, 1.5, 1.5, 300, 10, 30, 350, 8, 40, 3000, 1.75, 2000, 400, 20, 0.15, 10, 5, 3, 300, 80, 4, 10, 20, 9]

for i in range(len(cols)-2):
    col = np.array(train_df[cols[i]].values.tolist())
    train_df[cols[i]] = np.where(col > limit[i//2], np.nan, col).tolist()

comp_19 = train_df[train_df["compliance_2019"] == 1]
comp_20 = train_df[train_df["compliance_2020"] == 1]

for i in range((len(cols))//2):
    comp_19 = comp_19.drop(columns = cols[i*2+1])
    comp_20 = comp_20.drop(columns = cols[i*2])

In [99]:
max_value = []
min_value = []

for i in range(len(comp_19.columns)-1):
    max_value.append(max(comp_19.max()[i], comp_20.max()[i]))
    min_value.append(min(comp_19.min()[i], comp_20.min()[i]))